//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeSorteosEnLinea.ServicioDeSorteos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioDeSorteos.IServicioDeSorteos")]
    public interface IServicioDeSorteos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ListarSorteos", ReplyAction="http://tempuri.org/IServicioDeSorteos/ListarSorteosResponse")]
        GestorDeSorteosEnLinea.Model.Sorteos[] ListarSorteos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ListarSorteos", ReplyAction="http://tempuri.org/IServicioDeSorteos/ListarSorteosResponse")]
        System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.Sorteos[]> ListarSorteosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/AgregarSorteosHistoricos", ReplyAction="http://tempuri.org/IServicioDeSorteos/AgregarSorteosHistoricosResponse")]
        void AgregarSorteosHistoricos(GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, int elIdDelSorteo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/AgregarSorteosHistoricos", ReplyAction="http://tempuri.org/IServicioDeSorteos/AgregarSorteosHistoricosResponse")]
        System.Threading.Tasks.Task AgregarSorteosHistoricosAsync(GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, int elIdDelSorteo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ListarSorteosHistoricos", ReplyAction="http://tempuri.org/IServicioDeSorteos/ListarSorteosHistoricosResponse")]
        GestorDeSorteosEnLinea.Model.SorteosHistorico[] ListarSorteosHistoricos(int elIdDelSorteo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ListarSorteosHistoricos", ReplyAction="http://tempuri.org/IServicioDeSorteos/ListarSorteosHistoricosResponse")]
        System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.SorteosHistorico[]> ListarSorteosHistoricosAsync(int elIdDelSorteo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ConsultarUnSorteo", ReplyAction="http://tempuri.org/IServicioDeSorteos/ConsultarUnSorteoResponse")]
        GestorDeSorteosEnLinea.Model.Sorteos ConsultarUnSorteo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ConsultarUnSorteo", ReplyAction="http://tempuri.org/IServicioDeSorteos/ConsultarUnSorteoResponse")]
        System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.Sorteos> ConsultarUnSorteoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/InactivarUnSorteo", ReplyAction="http://tempuri.org/IServicioDeSorteos/InactivarUnSorteoResponse")]
        void InactivarUnSorteo(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, string laDescripcionDeLaModificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/InactivarUnSorteo", ReplyAction="http://tempuri.org/IServicioDeSorteos/InactivarUnSorteoResponse")]
        System.Threading.Tasks.Task InactivarUnSorteoAsync(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, string laDescripcionDeLaModificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ActivarUnSorteo", ReplyAction="http://tempuri.org/IServicioDeSorteos/ActivarUnSorteoResponse")]
        void ActivarUnSorteo(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, string laDescripcionDeLaModificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ActivarUnSorteo", ReplyAction="http://tempuri.org/IServicioDeSorteos/ActivarUnSorteoResponse")]
        System.Threading.Tasks.Task ActivarUnSorteoAsync(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, string laDescripcionDeLaModificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/AgregarSorteos", ReplyAction="http://tempuri.org/IServicioDeSorteos/AgregarSorteosResponse")]
        void AgregarSorteos(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/AgregarSorteos", ReplyAction="http://tempuri.org/IServicioDeSorteos/AgregarSorteosResponse")]
        System.Threading.Tasks.Task AgregarSorteosAsync(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ConsultarUnUsuario", ReplyAction="http://tempuri.org/IServicioDeSorteos/ConsultarUnUsuarioResponse")]
        GestorDeSorteosEnLinea.Model.AspNetUsers ConsultarUnUsuario(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ConsultarUnUsuario", ReplyAction="http://tempuri.org/IServicioDeSorteos/ConsultarUnUsuarioResponse")]
        System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.AspNetUsers> ConsultarUnUsuarioAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ListarSorteosCerrados", ReplyAction="http://tempuri.org/IServicioDeSorteos/ListarSorteosCerradosResponse")]
        GestorDeSorteosEnLinea.Model.Sorteos[] ListarSorteosCerrados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteos/ListarSorteosCerrados", ReplyAction="http://tempuri.org/IServicioDeSorteos/ListarSorteosCerradosResponse")]
        System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.Sorteos[]> ListarSorteosCerradosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioDeSorteosChannel : GestorDeSorteosEnLinea.ServicioDeSorteos.IServicioDeSorteos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDeSorteosClient : System.ServiceModel.ClientBase<GestorDeSorteosEnLinea.ServicioDeSorteos.IServicioDeSorteos>, GestorDeSorteosEnLinea.ServicioDeSorteos.IServicioDeSorteos {
        
        public ServicioDeSorteosClient() {
        }
        
        public ServicioDeSorteosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDeSorteosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDeSorteosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDeSorteosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GestorDeSorteosEnLinea.Model.Sorteos[] ListarSorteos() {
            return base.Channel.ListarSorteos();
        }
        
        public System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.Sorteos[]> ListarSorteosAsync() {
            return base.Channel.ListarSorteosAsync();
        }
        
        public void AgregarSorteosHistoricos(GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, int elIdDelSorteo) {
            base.Channel.AgregarSorteosHistoricos(elSorteoHistorico, elIdDelSorteo);
        }
        
        public System.Threading.Tasks.Task AgregarSorteosHistoricosAsync(GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, int elIdDelSorteo) {
            return base.Channel.AgregarSorteosHistoricosAsync(elSorteoHistorico, elIdDelSorteo);
        }
        
        public GestorDeSorteosEnLinea.Model.SorteosHistorico[] ListarSorteosHistoricos(int elIdDelSorteo) {
            return base.Channel.ListarSorteosHistoricos(elIdDelSorteo);
        }
        
        public System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.SorteosHistorico[]> ListarSorteosHistoricosAsync(int elIdDelSorteo) {
            return base.Channel.ListarSorteosHistoricosAsync(elIdDelSorteo);
        }
        
        public GestorDeSorteosEnLinea.Model.Sorteos ConsultarUnSorteo(int id) {
            return base.Channel.ConsultarUnSorteo(id);
        }
        
        public System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.Sorteos> ConsultarUnSorteoAsync(int id) {
            return base.Channel.ConsultarUnSorteoAsync(id);
        }
        
        public void InactivarUnSorteo(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, string laDescripcionDeLaModificacion) {
            base.Channel.InactivarUnSorteo(elSorteo, elSorteoHistorico, laDescripcionDeLaModificacion);
        }
        
        public System.Threading.Tasks.Task InactivarUnSorteoAsync(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, string laDescripcionDeLaModificacion) {
            return base.Channel.InactivarUnSorteoAsync(elSorteo, elSorteoHistorico, laDescripcionDeLaModificacion);
        }
        
        public void ActivarUnSorteo(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, string laDescripcionDeLaModificacion) {
            base.Channel.ActivarUnSorteo(elSorteo, elSorteoHistorico, laDescripcionDeLaModificacion);
        }
        
        public System.Threading.Tasks.Task ActivarUnSorteoAsync(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico, string laDescripcionDeLaModificacion) {
            return base.Channel.ActivarUnSorteoAsync(elSorteo, elSorteoHistorico, laDescripcionDeLaModificacion);
        }
        
        public void AgregarSorteos(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico) {
            base.Channel.AgregarSorteos(elSorteo, elSorteoHistorico);
        }
        
        public System.Threading.Tasks.Task AgregarSorteosAsync(GestorDeSorteosEnLinea.Model.Sorteos elSorteo, GestorDeSorteosEnLinea.Model.SorteosHistorico elSorteoHistorico) {
            return base.Channel.AgregarSorteosAsync(elSorteo, elSorteoHistorico);
        }
        
        public GestorDeSorteosEnLinea.Model.AspNetUsers ConsultarUnUsuario(string id) {
            return base.Channel.ConsultarUnUsuario(id);
        }
        
        public System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.AspNetUsers> ConsultarUnUsuarioAsync(string id) {
            return base.Channel.ConsultarUnUsuarioAsync(id);
        }
        
        public GestorDeSorteosEnLinea.Model.Sorteos[] ListarSorteosCerrados() {
            return base.Channel.ListarSorteosCerrados();
        }
        
        public System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.Sorteos[]> ListarSorteosCerradosAsync() {
            return base.Channel.ListarSorteosCerradosAsync();
        }
    }
}
