//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeSorteosEnLinea.ServiciosDeCorreo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosDeCorreo.IServiciosDeCorreo")]
    public interface IServiciosDeCorreo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosDeCorreo/EnviarCorreoNormal", ReplyAction="http://tempuri.org/IServiciosDeCorreo/EnviarCorreoNormalResponse")]
        bool EnviarCorreoNormal(string elEmailReceptor, string elNombre, string elMensajeAEnviar, string elAsunto, string laContrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosDeCorreo/EnviarCorreoNormal", ReplyAction="http://tempuri.org/IServiciosDeCorreo/EnviarCorreoNormalResponse")]
        System.Threading.Tasks.Task<bool> EnviarCorreoNormalAsync(string elEmailReceptor, string elNombre, string elMensajeAEnviar, string elAsunto, string laContrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosDeCorreo/ConsultarUnUsuarioPorNombre", ReplyAction="http://tempuri.org/IServiciosDeCorreo/ConsultarUnUsuarioPorNombreResponse")]
        GestorDeSorteosEnLinea.Model.AspNetUsers ConsultarUnUsuarioPorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosDeCorreo/ConsultarUnUsuarioPorNombre", ReplyAction="http://tempuri.org/IServiciosDeCorreo/ConsultarUnUsuarioPorNombreResponse")]
        System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.AspNetUsers> ConsultarUnUsuarioPorNombreAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosDeCorreoChannel : GestorDeSorteosEnLinea.ServiciosDeCorreo.IServiciosDeCorreo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosDeCorreoClient : System.ServiceModel.ClientBase<GestorDeSorteosEnLinea.ServiciosDeCorreo.IServiciosDeCorreo>, GestorDeSorteosEnLinea.ServiciosDeCorreo.IServiciosDeCorreo {
        
        public ServiciosDeCorreoClient() {
        }
        
        public ServiciosDeCorreoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosDeCorreoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosDeCorreoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosDeCorreoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EnviarCorreoNormal(string elEmailReceptor, string elNombre, string elMensajeAEnviar, string elAsunto, string laContrasena) {
            return base.Channel.EnviarCorreoNormal(elEmailReceptor, elNombre, elMensajeAEnviar, elAsunto, laContrasena);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarCorreoNormalAsync(string elEmailReceptor, string elNombre, string elMensajeAEnviar, string elAsunto, string laContrasena) {
            return base.Channel.EnviarCorreoNormalAsync(elEmailReceptor, elNombre, elMensajeAEnviar, elAsunto, laContrasena);
        }
        
        public GestorDeSorteosEnLinea.Model.AspNetUsers ConsultarUnUsuarioPorNombre(string nombre) {
            return base.Channel.ConsultarUnUsuarioPorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<GestorDeSorteosEnLinea.Model.AspNetUsers> ConsultarUnUsuarioPorNombreAsync(string nombre) {
            return base.Channel.ConsultarUnUsuarioPorNombreAsync(nombre);
        }
    }
}
